### ISSUE TITLE
Looking forward to adding reference papers

### ISSUE THREAD

**Issue by KennethYangle** [kirloyal/Distributed_Kalman_Filter#1]
Hi, Kirloyal:
I'm very interested in this repo! I'm researching distributed fusion algorithm and found this. It compare different fusion method and really work!
Could you add references for each method? So that I can study the code in combination with theoretical knowledge.
Thank you~

**Comment by ohkwon718** [comment]
Hi, I did it as a term project in the lecture "Advanced Sensor Data Fusion in Distributed Systems" at the University of Bonn.
https://net.cs.uni-bonn.de/de/wg/sdf/mitarbeiter/felix-govaers/

Btw, I saw your post regarding this repo.
https://kennethyang.gitee.io/2020/07/06/distributed-fusion/

So please attach this link on your post
https://github.com/ohkwon718/Distributed_Kalman_Filter

**Comment by KennethYangle** [comment]
Thank you for your reply! 
Would you like to provide more help, like courseware or article names of these fusion methods.

And, I update the blog on [https://kennethyang.gitee.io/2020/07/06/distributed-fusion/](url).
